version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: shareit
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shareit_network

volumes:
  postgres_data:

networks:
  shareit_network: